---
author: 
  - name: Anna Kreshuk
    orcid: 
    affiliations:
      - name: European Molecular Biology Laboratory
        country: Germany
  - name: Add any co-authors as appropriate
    orcid: 
    affiliations:
      - name: 
        state: 
        country: 
        postal-code: 
subtitle: What can AI enable for biology?
---

# Outlook

<!--Your first header will be the chapter's upper-level table of contents title.-->
<!--If you'd like to have a subtitle, include it in the Quarto header above -->

Under your first header, include a brief introduction to your chapter.

Starting prompt for this chapter: Chapter 11 concludes the book with a forward-looking assessment of AI in microscopy, focusing on how it can/will enable biological discovery. It should highlight a few motivational examples of discoveries that AI has already enabled and discuss opportunities to which the reader is primed to contribute after reading this book. 

## Adding to the Glossary

We are using R code to create a glossary for this book. To add a definition, edit the glossary.yml file. To reference the glossary, enclose the word as in these examples: LLMs suffer from [hallucinations](glossary.qmdl#hallucinations). It is important to understand the underlying [training data](glossary.qmd#trainingdata) to interpret your results. Clicking on the word will reveal its definition by taking you to the entry on the [Glossary](glossary.qmd) page. Pressing back in your browser will return you to your previous place in the textbook. 

## Tests

You might want to know about [power](glossary.qmd#power) or [false positives](glossary.qmd#falsepositives).


