project:
  type: book

book:
  title: "AI in Focus"
  subtitle: "Machine Learning for BioImaging"
  downloads: "pdf"
  license: "CC-BY"
  cover-image: cover.png
  editor: 
    - Owen Puls
    - Rachel Lee
    - Teng-Leong Chew
  chapters:
    - index.qmd
    - 1-intro.qmd
    - part: "Getting Started with AI"
      chapters:
       - 2-primer.qmd
    - outlook.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



